---
- name: MySQL slow query log analyzes job.
  cron:
    user: mysql
    name: 'MySQL slow query log analyze'
    minute: "{{ 60 | random(seed=ansible_hostname) }}"
    hour: '0'
    job: '/bin/sh /usr/local/bin/mysqlsla_analyzes.sh'